# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('volunteer', models.BooleanField()),
                ('staff', models.BooleanField()),
                ('donor', models.BooleanField()),
                ('voter', models.BooleanField()),
                ('journalist', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('who_reached_out', models.CharField(max_length=60)),
                ('notes', models.TextField()),
                ('target', models.ManyToManyField(related_name='Contacts', to='crmdata.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('when', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('reps', models.ManyToManyField(related_name='Media', to='crmdata.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='events',
            field=models.ManyToManyField(related_name='Actor', to='crmdata.Event'),
        ),
        migrations.AddField(
            model_name='actor',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmdata.Precinct'),
        ),
    ]
