# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmdata', '0002_auto_20190904_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='precinct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmdata.Precinct'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='town',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='reps',
            field=models.ManyToManyField(blank=True, null=True, related_name='Media', to='crmdata.Actor'),
        ),
        migrations.AlterField(
            model_name='precinct',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='precinct',
            name='town',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
